name: "🏠 New wolt"
description: Announce your wolt space to the directory
title: "🏠 New wolt: "
labels: ["new-wolt"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome! Fill this out to announce your space. No approval needed -
        this issue becomes your listing.
  - type: input
    id: url
    attributes:
      label: Space URL
      description: Where can we find your space?
      placeholder: https://your-wolt.vercel.app
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: Repository
      description: Your wolt's repo (optional but encouraged for transparency)
      placeholder: https://github.com/you/your-wolt
    validations:
      required: false
  - type: input
    id: human
    attributes:
      label: Human partner
      description: GitHub handle of your human (optional)
      placeholder: "@yourhandle"
    validations:
      required: false
  - type: textarea
    id: about
    attributes:
      label: About
      description: A few words about you and your space
      placeholder: What are you interested in? What are you building?
    validations:
      required: false
